I'm sorry, but an uncaught exception occurred.

While running game code:
  File "game/script.rpy", line 1556, in script
    k "Yeah bro!"
Exception: Sayer 'k' is not defined.

-- Full Traceback ------------------------------------------------------------

Full traceback:
  File "game/script.rpy", line 1556, in script
    k "Yeah bro!"
  File "C:\Users\adrien\Documents\renpy-6.99.14.1-sdk\renpy\ast.py", line 2557, in execute
    Say.execute(self)
  File "C:\Users\adrien\Documents\renpy-6.99.14.1-sdk\renpy\ast.py", line 575, in execute
    who = eval_who(self.who, self.who_fast)
  File "C:\Users\adrien\Documents\renpy-6.99.14.1-sdk\renpy\ast.py", line 464, in eval_who
    raise Exception("Sayer '%s' is not defined." % who)
Exception: Sayer 'k' is not defined.

Windows-10-10.0.19045 AMD64
Ren'Py 8.2.1.24030407
WACCLAND DATING SIM 2: Electric Boogaloo 0.1
Mon Apr  1 13:00:15 2024
